//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using BlazorBoilerplate.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class BaseAuditableEntity : BaseEntity, IBaseAuditableEntity
    {
        public DateTime CreatedOn
        {
            get { return GetValue<DateTime>(); }
            set { SetValue(value); }
        }

        public DateTime? ModifiedOn
        {
            get { return GetValue<DateTime?>(); }
            set { SetValue(value); }
        }

        IApplicationUser IBaseAuditableEntity.CreatedBy { get => CreatedBy; set => CreatedBy = (ApplicationUser)value; }

        public ApplicationUser CreatedBy
        {
            get { return GetValue<ApplicationUser>(); }
            set { SetValue(value); }
        }

        public Guid? CreatedById
        {
            get { return GetValue<Guid?>(); }
            set { SetValue(value); }
        }

        IApplicationUser IBaseAuditableEntity.ModifiedBy { get => ModifiedBy; set => ModifiedBy = (ApplicationUser)value; }

        public ApplicationUser ModifiedBy
        {
            get { return GetValue<ApplicationUser>(); }
            set { SetValue(value); }
        }

        public Guid? ModifiedById
        {
            get { return GetValue<Guid?>(); }
            set { SetValue(value); }
        }

    }
}
